name: reverse-proxy docker image
on: [push]
jobs:

  build:
    runs-on: self-hosted
    env:
      tag: latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.org_blocknetdximg_password }} | docker login --username ${{ secrets.org_blocknetdximg_username }} --password-stdin 
    - name: Image info
      run: echo Building ${{ github.workflow }} ${{ github.ref_name }}
    - name: Set tag to branch name if not on master
      if: github.ref_name != 'master'
      run: echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
    - name: Build an image
      working-directory: reverse-proxy
      run: docker build . --file Dockerfile --tag blocknetdx/xquery-reverse-proxy:${{ env.tag }}
    - name: Push image
      run: docker push blocknetdx/xquery-reverse-proxy:${{ env.tag }}
    - name: Remove dangling images
      if: ${{ always() }}
      run: yes | docker image prune
